"""Ejemplo de uso de la plantilla factory_zr.py."""

import sys
from airflow.models import Variable

path_utils = Variable.get("PATH_DAG_UTILS", default_var="./dags")
sys.path.append(f"{path_utils}")
import factory_zr


# ============================================================================
# CONFIGURACIÓN DE DAGS
# ============================================================================
# NOTA: No es necesario definir global_config ni operator_config.
#       El factory usa configuración por defecto automáticamente.
#       Solo define configs personalizadas si necesitas overrides específicos.
# ============================================================================

DAGS_CONFIG = [
    {
        # dag de wtteller
        "dag_id": "dag_oracle_fcm_tablas_cobros",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "2 5 * * *",
        "flujos": [
            # Flujo con sensor - inicia a las 02:00 AM
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DEPOSIT_HEADER_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_deposit_header_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DEPOSIT_DETAIL_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_deposit_detail_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_RECEIVABLES_ENRICHMENT_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_receivables_enrichment_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DEPOSITHEADER",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_depositheader",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DEPOSITDETAIL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_depositdetail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_LIQUIDATION_DETAIL_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_liquidation_detail_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_RECEIVABLES",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_kustom_receivables",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_RECEIVABLES_BATCH",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_kustom_receivables_batch",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_HOST_COLL_ACCT_HANDOFF",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_host_coll_acct_handoff",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaRaw"],
        "description": "DAG de carga de información a ZR de oracle fcm grupo tablas cobros",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_pago_recaudo",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "2 5 * * *",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_MONEY_TRANSFER_ERROR",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_money_transfer_error",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_ENRICHMENT_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_enrichment_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PIRHEADER",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_pirheader",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PIR_HEADER_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_pir_header_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PIRDETAIL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_pirdetail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PIR_DETAIL_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_pir_detail_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_HOST_PAY_TXN_HANDOFF_HEADER",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_host_pay_txn_handoff_header",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_HOST_PAY_TXN_HANDOFF_DETAIL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_host_pay_txn_handoff_detail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_COLLECTION_REVERSAL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_kustom_collection_reversal",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaRaw"],
        "description": "DAG de carga de información a ZR de oracle fcm grupo tablas pago recaudo",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_comision",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "2 5 * * *",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_COMISSION",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_kustom_comission",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_TAX",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_kustom_tax",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CHARGE_POSTING_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_charge_posting_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CHARGE_COMPUTE_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_charge_compute_txn",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaRaw"],
        "description": "DAG de carga de información a ZR de oracle fcm grupo tablas comision",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_catalogos",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "2 5 * * *",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DRAWEE_BANK_BRANCH_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_drawee_bank_branch_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_RECEIVABLE_PACKAGE_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_receivable_package_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PRODUCT_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_product_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_BANK_PRODUCT_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_bank_product_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CLIENT_SERVICE_SETUP",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_client_service_setup",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_GEN_PRELOAD_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_gen_preload_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_ACCOUNT_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_cpon_account_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PRF_CHARGE_FRQ_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_prf_charge_frq_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PAYMENT_PACKAGE_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_payment_package_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_PAGO_TARJETAS_WEBTELLER",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_pago_tarjetas_webteller",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_SRI_CODES_RATES",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_sri_codes_rates",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaRaw"],
        "description": "DAG de carga de información a ZR de oracle fcm grupo tablas catalogos",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_configuracion",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "2 5 * * *",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_PAY_PKG_LINKAGE",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_cpon_pay_pkg_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_REC_PKG_LINKAGE",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_cpon_rec_pkg_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_PAY_PKG_ACT_LINKAGE",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_cpon_pay_pkg_act_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_REC_PKG_ACT_LINKAGE",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_cpon_rec_pkg_act_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CATEGORYMASTER",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_categorymaster",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CATEGORY_PRODUCT_LINKAGE",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_category_product_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CATEGORY_ACCOUNT_LINKAGE",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_category_account_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_USERCLIENTRIGHTS",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_userclientrights",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_USERPRODUCTS",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_userproducts",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_USERMASTER",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_usermaster",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_USERACCOUNTS",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_useraccounts",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_TCW_AUTHMATRIX_MASTER",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_tcw_authmatrix_master",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_TCW_AUTHMATRIX_DETAIL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_tcw_authmatrix_detail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_TCW_AUTHMATRIX_WORKFLOW_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_tcw_authmatrix_workflow_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_TCW_AUTHMATRIX_WORKFLOW_DTL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_tcw_authmatrix_workflow_dtl",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PRF_CHARGE_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_prf_charge_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PRF_CHARGE_DTL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_prf_charge_dtl",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CHARGE_UNITS_DTL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_charge_units_dtl",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CHARGE_UNITS_RULE_DTL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_charge_units_rule_dtl",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaRaw"],
        "description": "DAG de carga de información a ZR de oracle fcm grupo tablas configuracion",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_recaudo_file",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "2 5 * * *",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_FILE_MST",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_file_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_DINERS",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_bills_diners",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_DINERS_DISCOVERY",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_bills_diners_discovery",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_DINERS_MASTERCARD",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_bills_diners_mastercard",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_DINERS_VISA",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_bills_diners_visa",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_PICHINCHA_DISCOVERY",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_bills_pichincha_discovery",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_PICHINCHA_MASTERCARD",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_bills_pichincha_mastercard",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_PICHINCHA_VISA",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_bills_pichincha_visa",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_VISA_BGR",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_bills_visa_bgr",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_BILLS",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_invoice_bills",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_BILLS_EXPIRED",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_invoice_bills_expired",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_TXN",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_invoice_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_TXN_DINVISA",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_invoice_txn_dinvisa",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_TXN_DINVISA_HISTORIC",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_invoice_txn_dinvisa_historic",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_TXN_EXPIRED",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_invoice_txn_expired",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_LEGACY_COLLECTIONS_DETAIL",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_legacy_collections_detail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_LEGACY_COLLECTIONS_HEADER",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_legacy_collections_header",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_SWEEPING_REPORT",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_sweeping_report",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_SWEEPING_REPORT_TRANSACTIONS",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_sweeping_report_transactions",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_SWEEPING_REPORT_TRANSACTIONS_DINVISA",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_sweeping_report_transactions_dinvisa",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_SWEEPING_RETRY",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_fc_sweeping_retry",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CUSTOM_UPLOAD_FILE_CONVERT",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_custom_upload_file_convert",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaRaw"],
        "description": "DAG de carga de información a ZR de oracle fcm grupo tablas recaundo file",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_impuestos",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "2 5 * * *",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_ISD",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_kustom_isd",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaRaw"],
        "description": "DAG de carga de información a ZR de oracle fcm grupo tablas impuestos",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_retencion",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "2 5 * * *",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_SIPECOM",
                "talla": "SparkResources",
                "nombre_tabla": "ZR_BP_Can_Cash_fcm_kustom_sipecom",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaRaw"],
        "description": "DAG de carga de información a ZR de oracle fcm grupo tablas retencion",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
]

# ============================================================================
# GENERACIÓN Y REGISTRO DE DAGS
# ============================================================================

factory_zr.register_dags(DAGS_CONFIG, globals())
