"""Ejemplo de uso de la plantilla factory_zr.py."""

import sys
from airflow.models import Variable

path_utils = Variable.get("PATH_DAG_UTILS", default_var="./dags")
sys.path.append(f"{path_utils}")
import factory_zr as factory_zr


# ============================================================================
# CONFIGURACIÓN DE DAGS
# ============================================================================
# NOTA: No es necesario definir global_config ni operator_config.
#       El factory usa configuración por defecto automáticamente.
#       Solo define configs personalizadas si necesitas overrides específicos.
# ============================================================================

DAGS_CONFIG = [
    {
        # dag de wtteller
        "dag_id": "dag_oracle_fcm_tablas_cobros_tt",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "None",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DEPOSIT_HEADER_TXN_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobrosOrdenes",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_deposit_header_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DEPOSIT_DETAIL_TXN_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobrosDetalleProcesadas",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_deposit_detail_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_RECEIVABLES_ENRICHMENT_TXN_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobrosItemsDetalle",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_receivables_enrichment_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DEPOSITHEADER_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobrosCabecera",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_depositheader",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DEPOSITDETAIL_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobrosDetalle",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_depositdetail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_LIQUIDATION_DETAIL_TXN_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobrosItemsProcesados",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_liquidation_detail_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_RECEIVABLES_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobrosItems",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_kustom_receivables",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_RECEIVABLES_BATCH_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobrosMovimientos",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_kustom_receivables_batch",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_HOST_COLL_ACCT_HANDOFF_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobrosMovimientosDebito",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_host_coll_acct_handoff",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaCurada"],
        "description": "DAG de carga de información a ZC de oracle fcm grupo tablas cobros",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_pago_recaudo_tt",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "None",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_MONEY_TRANSFER_ERROR_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_LogErroresTransferencias",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_money_transfer_error",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_ENRICHMENT_TXN_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_PagosRecaudosItemsDetalle",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_enrichment_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PIRHEADER_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_PagosRecaudosCabecera",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_pirheader",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PIR_HEADER_TXN_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_PagosRecaudosOrdenes",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_pir_header_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PIRDETAIL_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_PagosRecaudosDetalle",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_pirdetail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PIR_DETAIL_TXN_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_PagosRecaudosItems",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_pir_detail_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_HOST_PAY_TXN_HANDOFF_HEADER_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_PagosRecaudosMovimientos",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_host_pay_txn_handoff_header",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_HOST_PAY_TXN_HANDOFF_DETAIL_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_PagosRecaudosMovimientosDetalle",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_host_pay_txn_handoff_detail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_COLLECTION_REVERSAL_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_PagosRecaudosReversos",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_kustom_collection_reversal",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaCurada"],
        "description": "DAG de carga de información a ZC de oracle fcm grupo tablas pago recaudo",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_comision_tt",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "None",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_COMISSION_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CobroComisiones",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_kustom_comission",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_TAX_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ImpuestoIVA",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_kustom_tax",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CHARGE_POSTING_TXN _TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ComisionCobrada",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_charge_posting_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CHARGE_COMPUTE_TXN_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ComisionCalculada",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_charge_compute_txn",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaCurada"],
        "description": "DAG de carga de información a ZC de oracle fcm grupo tablas comision",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_catalogos_td",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "None",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_DRAWEE_BANK_BRANCH_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_EntidadesBancarias",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_drawee_bank_branch_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_RECEIVABLE_PACKAGE_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_PaquetesCobros",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_receivable_package_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PRODUCT_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_Productos",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_product_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_BANK_PRODUCT_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_FormasPago",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_bank_product_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CLIENT_SERVICE_SETUP_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_ConfiguracionEmpresaCliente",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_client_service_setup",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_GEN_PRELOAD_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_Estados",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_gen_preload_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_ACCOUNT_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_Cuentas",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_cpon_account_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PRF_CHARGE_FRQ_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_FrecuenciaCargaComision",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_prf_charge_frq_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PAYMENT_PACKAGE_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_PaquetesPagos",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_payment_package_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_PAGO_TARJETAS_WEBTELLER_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_RecaudosTarjetasWebteller",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_pago_tarjetas_webteller",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_SRI_CODES_RATES_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_TarifasSri",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_sri_codes_rates",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaCurada"],
        "description": "DAG de carga de información a ZC de oracle fcm grupo tablas catalogos",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_configuracion_tt",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "None",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_PAY_PKG_LINKAGE_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_PagoServicioCuenta",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_cpon_pay_pkg_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_REC_PKG_LINKAGE_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_CobroServicioCuenta",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_cpon_rec_pkg_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_PAY_PKG_ACT_LINKAGE_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_PagoClienteCuenta",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_cpon_pay_pkg_act_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CPON_REC_PKG_ACT_LINKAGE_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_CobroClienteCuenta",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_cpon_rec_pkg_act_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CATEGORYMASTER_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_RolUsuario",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_categorymaster",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CATEGORY_PRODUCT_LINKAGE_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_RolProducto",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_category_product_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CATEGORY_ACCOUNT_LINKAGE_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_RolCuenta",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_category_account_linkage",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_USERCLIENTRIGHTS_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_ClienteUsuario",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_userclientrights",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_USERPRODUCTS_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_UsuarioProducto",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_userproducts",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_USERMASTER_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_Usuario",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_usermaster",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_USERACCOUNTS_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_CuentaUsuario",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_useraccounts",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_TCW_AUTHMATRIX_MASTER_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_AprobacionMatrices",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_tcw_authmatrix_master",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_TCW_AUTHMATRIX_DETAIL_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_DetalleAprobacionMatrices",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_tcw_authmatrix_detail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_TCW_AUTHMATRIX_WORKFLOW_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_FlujoMatrices",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_tcw_authmatrix_workflow_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_TCW_AUTHMATRIX_WORKFLOW_DTL_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_DetalleFlujoMatrices",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_tcw_authmatrix_workflow_dtl",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PRF_CHARGE_MST_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_Tarifa",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_prf_charge_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_PRF_CHARGE_DTL_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_DetalleTarifa",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_prf_charge_dtl",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CHARGE_UNITS_DTL_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_TarifaServicio",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_charge_units_dtl",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CHARGE_UNITS_RULE_DTL_TD",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TD_ReglasTarifa",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_charge_units_rule_dtl",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaCurada"],
        "description": "DAG de carga de información a ZC de oracle fcm grupo tablas configuracion",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_recaudo_file_tt",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "None",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_FILE_MST_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_MaestroOrdenesArchivos",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_file_mst",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_DINERS_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_OrdenesTarjetaCreditoDiners",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_bills_diners",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_DINERS_DISCOVERY_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_OrdenesTarjetaCreditoDinersDiscover",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_bills_diners_discovery",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_DINERS_MASTERCARD_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_OrdenesTarjetaCreditoDinersMastercard",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_bills_diners_mastercard",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_DINERS_VISA_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_OrdenesTarjetaCreditoDinersVisa",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_bills_diners_visa",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_PICHINCHA_DISCOVERY_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_OrdenesTarjetaCreditoPichinchaDiscover",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_bills_pichincha_discovery",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_PICHINCHA_MASTERCARD_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_OrdenesTarjetaCreditoPichinchaMastercard",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_bills_pichincha_mastercard",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_PICHINCHA_VISA_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_OrdenesTarjetaCreditoPichinchaVisa",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_bills_pichincha_visa",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_BILLS_VISA_BGR_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_OrdenesTarjetaCreditoVisaBrg",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_bills_visa_bgr",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_BILLS_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ItemsRecaudacion",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_invoice_bills",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_BILLS_EXPIRED_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ItemsExpiradoRecaudacion",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_invoice_bills_expired",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_TXN_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ItemsMovimientosRecaudaciones",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_invoice_txn",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_TXN_DINVISA_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ItemsMovimientosDinVisa",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_invoice_txn_dinvisa",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_TXN_DINVISA_HISTORIC_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ItemsMovimientosDinVisaHistorica",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_invoice_txn_dinvisa_historic",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_INVOICE_TXN_EXPIRED_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ItemsMovimientosExpiradosRecaudaciones",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_invoice_txn_expired",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_LEGACY_COLLECTIONS_DETAIL_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_DetalleArchivosLegados",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_legacy_collections_detail",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_LEGACY_COLLECTIONS_HEADER_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CabeceraArchivosLegados",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_legacy_collections_header",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_SWEEPING_REPORT_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ReporteCabeceraAcreditaciones",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_sweeping_report",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_SWEEPING_REPORT_TRANSACTIONS_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ReporteDetalleAcreditaciones",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_sweeping_report_transactions",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_SWEEPING_REPORT_TRANSACTIONS_DINVISA_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ReporteDetalleAcreditacionesDinVisa",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_sweeping_report_transactions_dinvisa",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_FC_SWEEPING_RETRY_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ReintentosAcreditacion",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_fc_sweeping_retry",
            },
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_CUSTOM_UPLOAD_FILE_CONVERT_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_CargaArchivos",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_custom_upload_file_convert",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaCurada"],
        "description": "DAG de carga de información a ZC de oracle fcm grupo tablas recaundo file",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_impuestos_tt",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "None",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_ISD_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_ImpuestoISD",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_kustom_isd",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaCurada"],
        "description": "DAG de carga de información a ZC de oracle fcm grupo tablas impuestos",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
    {
        "dag_id": "dag_oracle_fcm_tablas_retencion_tt",
        "codigo_malla": "EMP_FCM_001",
        "schedule": "None",
        "flujos": [
            {
                "workflow_name": "pl-ingesta-Uti-MotorTablas",
                "id_ingesta": "CAN_KUSTOM_SIPECOM_TT",
                "talla": "SparkResources",
                "nombre_tabla": "ZC_BP_Can_Cash_TT_FacturacionRetenciones",
                "dataset_origen": "ZR_BP_Can_Cash_fcm_kustom_sipecom",
            },
        ],
        "tags": ["tribe: can", "cell: datos", "domain: cash", "type: DataZonaCurada"],
        "description": "DAG de carga de información a ZC de oracle fcm grupo tablas retencion",
        "owner": "sperezpe",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 3,
        "retry_delay_minutes": 5,
        "catchup": False,
        "max_active_runs": 1,
        "dagrun_timeout_minutes": 1200,
        "start_year": 2026,
        "start_month": 1,
        "start_day": 20,
    },
]

# ============================================================================
# GENERACIÓN Y REGISTRO DE DAGS
# ============================================================================

factory_zr.register_dags(DAGS_CONFIG, globals())
